### PR TITLE
Adding the timing of each post

### PR DESCRIPTION
**Pull request by minukumari**
Hello,

This is the pull request regarding issue "Display the post time #130".
I have added a feature for displaying on which date the post is posted.

Example - In this given picture it is showing like "Posted 2 hours ago"

image

In this given picture it is showing like "Posted 4 days ago"

image

After 10 days it start showing the date on which it is posted.
Here it is showing like "Posted on 27/03/2021"

image

if there is any correction let me know.

### CODE REVIEW

**Review by Utkarsh1999 — CHANGES_REQUESTED** [review]
@minukumari  kindly resolve the conflicts.

**Comment by minukumari** [comment]
@Utkarsh1999  conflicts are resolved.

**Review by Utkarsh1999 — APPROVED** [review]

**Comment by avinashkranjan** [comment]
@minukumari Resolve the conflicts

**Comment by minukumari** [comment]
@avinashkranjan conflicts are resolved. Kindly review it.

**Review by avinashkranjan — APPROVED** [review]

**Comment by Utkarsh1999** [comment]
@minukumari , please resolve the conflicts.

**Pull request closed without merging**
