### PR TITLE
Issue #52 Add comment funtionality.

### PR DESCRIPTION
**Pull request by kokilgupta**
Created a comment icon so that the comments will be visible only when user clicks on the icon.

Screenshot (245)

### CODE REVIEW

**Comment by abhishek2x** [comment]
Hey @kokilgupta, kindly create an issue for the Same, we need that for documentation

**Comment by kokilgupta** [comment]
I have already created a issue https://github.com/avinashkranjan/Recess/issues/52

**Review by abhishek2x — APPROVED** [review]

**Comment by abhishek2x** [comment]
There are some conflicts, kindly resolve them. Rest LGTM.

**Review by Utkarsh1999 — CHANGES_REQUESTED** [review]
@kokilgupta , resolve the conflicts

**Pull request closed without merging**
