### PR TITLE
github authentication added

### PR DESCRIPTION
**Pull request by Ankita297**
## Related Issue 
github authentication added
Closes: #201 

### Describe the changes you've made
I have added github authentication through firebase 
Give a clear description what modifications you have made

## Type of change

What sort of change have you made:

- [x ] Bug fix (non-breaking change which fixes an issue)
- [ x] New feature (non-breaking change which adds functionality)
- [ x] Code style update (formatting, local variables)
- [ x] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ x] This change requires a documentation update

## Mention any unusual behaviour of your code (Write NA if not)
NA
## Checklist:

- [x ] My code follows the guidelines of this project.
- [x ] I have performed a self-review of my own code.
- [x ] I have commented my code, particularly whereever it was hard to understand.
- [x ] My changes generate no new warnings.
- [x ] Any dependent changes have been merged and published in downstream modules.

## Screenshots
Add Screenshots to show your changes 

## Additional Info (optional)
Any additional information you want to give
Recess - Students Social Media - Google Chrome 06-05-2021 20_56_01

### CODE REVIEW

**Comment by Ankita297** [comment]
@avinashkranjan @Utkarsh1999 Sir  Please review my PR  and you have not enabled github auth . So please enable it .

**Comment by Utkarsh1999** [comment]
@avinashkranjan , enable GitHub auth.

> 
> 
> @avinashkranjan @Utkarsh1999 Sir Please review my PR and you have not enabled GitHub auth. So please enable it.

**Comment by Ankita297** [comment]
@Utkarsh1999 can i also work on facebook auth . I have done the coding part and it is working fine .So can i make the PR for that ?
I have also asked for issue ?

**Comment by Ankita297** [comment]
@avinashkranjan @Utkarsh1999 Please review my PR .

**Comment by Utkarsh1999** [comment]
> 
> 
> @Utkarsh1999 can i also work on facebook auth . I have done the coding part and it is working fine .So can i make the PR for that ?
> I have also asked for issue ?

Yes you, but please create an issue for that.

**Comment by Ankita297** [comment]
@Utkarsh1999 issue is already created but it is assigned to someone  else .

**Comment by Utkarsh1999** [comment]
> 
> 
> @Utkarsh1999 issue is already created but it is assigned to someone else.

I assigned that to you, go ahead with Facebook auth.

**Comment by Ankita297** [comment]
@Utkarsh1999  @avinashkranjan  have you disabled the facebook auth ?

**Review by abhishek2x — CHANGES_REQUESTED** [review]
Looks fine but there is an issue. You have created the same function `githubSignIn` two times in different files. Good practice will be if you create all authentication function in a single file and pass them through props.

**Review by abhishek2x — APPROVED** [review]
LGTM

**Review by avinashkranjan — APPROVED** [review]

**Pull request merged**
