### PR TITLE
Issue #61 : Show Toast/notifications on user signup and signin

### PR DESCRIPTION
**Pull request by nitinNT**
@avinashkranjan Added the Toast / Notifications on user sign up 

screenshots of required functionality :
image
 

Kindly Review it

### CODE REVIEW

**Comment by abhishek2x** [comment]
Hey @nitinNT, there are some conflicts that need to be resolved. Kindly look into them.

**Review by Utkarsh1999 — CHANGES_REQUESTED** [review]
@nitinNT  Kindly, resolve all the conflicts.

**Comment by nitinNT** [comment]
Reviewers , Please Check now

**Comment by Utkarsh1999** [comment]
image

@nitinNT , It's really difficult to review these many files. please squash your commits.

**Comment by nitinNT** [comment]
@Utkarsh1999 can you plese tell me how to squash the other commits or how to do this . 
Sorry , I'm new to this 

Thank You

**Comment by avinashkranjan** [comment]
Hey @nitinNT, Kindly Create a new PR for the Same..

**Pull request closed without merging**
