### PR TITLE
Added Dark Mode and Restructured Files

### PR DESCRIPTION
**Pull request by Jaagrav**
## Restructured Files
The initial file structure did not include of some very important folders. Considering this project grows more in the future, when more pages would be added, it would be a jungle of files, hence I added two more folders to organize the files in a way that makes more sense.

image

The new  **file system rules** are as follows:

- Follow Pascal Case Naming of folders, for e.g. ComponentName, the first letter of every word is capitalized.
- Every page has it's own folder, for e.g. HomePage, create a folder with a path like this, `./src/pages/HomePage`
- All the main code of the individual pages must include an index.js and a style.css for e.g. `./src/pages/HomePage/index.js` and `./src/pages/HomePage/style.css`, this would make it easy to import the page to App.js just by using `import HomePage from '../pages/HomePage';`
- Every component would go into the components folder, for e.g. `./src/components/Post`.
- Similar to the pages rules, every component would follow Pascal Case naming and also would include both index.js and style.css just to make it common for every other component.

## Added Dark Mode
Dark mode
Once you merge this PR, you'll notice a dark mode icon on the top-right corner, near auth buttons, when clicked it changes the theme of the website. 

> What's under the hood?

In order to add this feature, I used **CSS Variables** whose values are changed everytime a boolean state variable called `darkModeOn`  changes. This state is changed every time the button shown above is clicked, and that's how the dark mode switch works. We can use Material UI's theme package but that would increase the bundle size, switching CSS variables and using them everytime would not only maintain the theme but also make it easy for us to switch between.

### CODE REVIEW

**Comment by Jaagrav** [comment]
Check out the deploy preview of the changes I made here: https://recess-4cnoaxe4v-jaagrav.vercel.app/

**Comment by Jaagrav** [comment]
This PR resolves issue #64

**Comment by abhishek2x** [comment]
@Jaagrav LGTM, but before moving forward, kindly resolve the conflicts.

**Comment by Jaagrav** [comment]
Deploy Preview: https://recess-gssoc.vercel.app/

**Review by Utkarsh1999 — CHANGES_REQUESTED** [review]
@Jaagrav ,

New Structure looks good, though there are some changes,
1. maintain an index.js file in the components folder, so that no one has to dig inside the component folder to import a particular component.
Index.js file in the component folder is just importing all the components and then exporting them so that this will behave more like a library.

2. same thing for the pages folder too.

3. add eslintcache file in gitignore

4. add package-lock.json in gitignore

rest looks good to me.

**Comment by Jaagrav** [comment]
I understand, I have been working on the new UI design where I have changed the file structure a bit more since I am using pure material UI styling for it, therefore for this PR I haven't committed those changes

**Comment by Utkarsh1999** [comment]
> 
> 
> @Utkarsh1999
> 
> I understand, I have been working on the new UI design where I have changed the file structure a bit more since I am using pure material UI styling for it, therefore for this PR I haven't committed those changes

issue number?

**Comment by Jaagrav** [comment]
#96

**Review by Utkarsh1999 — APPROVED** [review]

**Review by avinashkranjan — APPROVED** [review]

**Comment by avinashkranjan** [comment]
@all-contributors please add @Jaagrav for code and design

**Pull request merged**
