### PR TITLE
Added auto reply for every successful merged  pull requests

### PR DESCRIPTION
**Pull request by AB-san**
## Related Issue 

- Info about the related issue 

Closes: #172 

### Describe the changes you've made

Give a clear description what modifications you have made

## Type of change

What sort of change have you made:

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, local variables)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## Mention any unusual behaviour of your code (Write NA if not)
Any unusual behaviour of your code

## Checklist:

- [x] My code follows the guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly whereever it was hard to understand.
- [x] My changes generate no new warnings.
- [x] Any dependent changes have been merged and published in downstream modules.

## Screenshots
The github action that i added looks like this -
image

## Additional Info (optional)
Any additional information you want to give

### CODE REVIEW

**Comment by AB-san** [comment]
> ## Related Issue
> * Info about the related issue
> 
> Closes: #172
> 
> ### Describe the changes you've made
> Give a clear description what modifications you have made
> 
> ## Type of change
> What sort of change have you made:
> 
> * [ ]  Bug fix (non-breaking change which fixes an issue)
> * [x]  New feature (non-breaking change which adds functionality)
> * [ ]  Code style update (formatting, local variables)
> * [ ]  Breaking change (fix or feature that would cause existing functionality to not work as expected)
> * [ ]  This change requires a documentation update
> 
> ## Mention any unusual behaviour of your code (Write NA if not)
> Any unusual behaviour of your code
> 
> ## Checklist:
> * [x]  My code follows the guidelines of this project.
> * [x]  I have performed a self-review of my own code.
> * [x]  I have commented my code, particularly whereever it was hard to understand.
> * [x]  My changes generate no new warnings.
> * [x]  Any dependent changes have been merged and published in downstream modules.
> 
> ## Screenshots
> The github action that i added looks like this -
> image
> 
> ## Additional Info (optional)
> Any additional information you want to give

**Comment by AB-san** [comment]
@Utkarsh1999 @avinashkranjan Mentors please kindly review this pr

**Comment by avinashkranjan** [comment]
@AB-san Kindly Have a Look the PR you've Created..You have pushed 2000+ files

**Comment by AB-san** [comment]
> @AB-san Kindly Have a Look the PR you've Created..You have pushed 2000+ files 

Yes 3 main pages - index.js , action.yml, My-workflow.yml and other files are node dependencies which are required to run the workflow (especially write the js file of the workflow).

If you want I can explain the use of each of the files

**Review by Utkarsh1999 — CHANGES_REQUESTED** [review]
Remove node_modules files from PR.

**Comment by AB-san** [comment]
> Remove node_modules files from PR.

Okay I will make those changes and push agn!

**Comment by AB-san** [comment]
@avinashkranjan @Utkarsh1999 I have updated my pr , this time I have used an external resource . Mentors please kindly review the pr

**Comment by Utkarsh1999** [comment]
why I and Avinash are added in exempted users? rest LGTM

**Review by Utkarsh1999 — APPROVED** [review]
Look good to me.

**Review by avinashkranjan — APPROVED** [review]

**Pull request merged**
