### PR TITLE
Updated Readme

### PR DESCRIPTION
**Pull request by itsIapetus**
Issue Number #56

### CODE REVIEW

**Comment by avinashkranjan** [comment]
Hey @itsIapetus It's already mentioned in CONTRIBUTING.md why add it in README..Kindly Resolve the Conflicts and Add Information about the Project in the README.

**Comment by itsIapetus** [comment]
Okay! sure!

**Comment by itsIapetus** [comment]
I think it doesn't need anything more, it looks complete.

**Comment by avinashkranjan** [comment]
So, Closing the Issue and PR..Look for Other Open issues.

**Pull request closed without merging**
