### PR TITLE
Issue : 88 Changed the look and case of the buttons using Material UI

### PR DESCRIPTION
**Pull request by lavanya243**
Hey,  @Utkarsh1999 @avinashkranjan  @abhishek2x 
https://user-images.githubusercontent.com/69483128/111121391-96ffd480-8592-11eb-9bc3-81fbe92540fb.mp4

I have attached a video which demonstrates the changes I have made.

The changes made are as follows:
1) I have changed the look and case of the buttons (sign up, sign in, log out and upload with  color changing on hover and click effect.
2) I have made changes in 4 files namely:  ImageUpload.js, ImageUpload.css, Homepage.js and Homepage.css
3) I have increased the left margin of the recess logo in the header section

Kindly Review the changes made.

### CODE REVIEW

**Review by Utkarsh1999 — CHANGES_REQUESTED** [review]
@lavanya243 , Kindly resolve the conflicts

**Comment by lavanya243** [comment]
> @lavanya243 , Kindly resolve the conflicts

@Utkarsh1999 Please grant permission for resolving conflicts.
SC

**Comment by Utkarsh1999** [comment]
Hey @lavanya243 , it would be better if you resolve these conflicts on your local machine.

**Comment by lavanya243** [comment]
Hi @Utkarsh1999 , I have made the required changes. Is it okay now?

**Pull request closed without merging**
