### PR TITLE
Modal to show all comments Issue #146

### PR DESCRIPTION
**Pull request by Inventor77**
## Changes Made 
-> Able to view all comment by clicking on "View Comment" button which makes appearance of  Modal 
-> On Modal, Post image will be on left side and all the comment on right side makes to view all the comments by scrolling

Closes: #[146]

## Type of change

- [ Y ] New feature (non-breaking change which adds functionality)
- [ Y ] Code style update (formatting, local variables)

## Mention any unusual behavior of your code (Write NA if not)
Any unusual behavior of your code 

## Checklist:

- [ Y ] My code follows the guidelines of this project.
- [ Y ] I have performed a self-review of my own code.
- [ Y ] I have commented my code, particularly wherever it was hard to understand.
- [ Y ] My changes generate no new warnings.

## GIF
Modal

### CODE REVIEW

**Comment by Inventor77** [comment]
@Utkarsh1999 @AnjaliSrivastava722  @avinashkranjan  Mentors Please overlooK on this PR and suggest any changes are required, if not Please merge it.

**Comment by Inventor77** [comment]
@avinashkranjan Sir please can you guide me , how more attractive modal I can make or Please can you ****``merge``**** this such that I can Create some more Issue and work on them

**Comment by avinashkranjan** [comment]
Hello @Inventor77 , Thanks for the PR, Kindly Make the following changes in the Design , Keep the Color Theme Intact cause this doesn't match the color, Bring the [x] Marker to one corner of the popup Add Comment Functionality to the opened popup..Rest LGTM

**Comment by Inventor77** [comment]
@avinashkranjan  Sir I have changed all the changes you asked , please tell me is their anything I should do more to it 


Screenshot (602)

**Comment by Inventor77** [comment]
@avinashkranjan Sir ```Issue #146``` is already closed. Will you please open the issue again or directly merge this PR . I have no Idea , I'm novice in GitHub please tell me about it

**Review by avinashkranjan — APPROVED** [review]
LGTM..

**Pull request merged**
