### PR TITLE
facebook authentication added

### PR DESCRIPTION
**Pull request by Ankita297**
## Related Issue 

facebook authentication added

Closes: #117 

### Describe the changes you've made

Give a clear description what modifications you have made

## Type of change

What sort of change have you made:

- [ x] Bug fix (non-breaking change which fixes an issue)
- [ x] New feature (non-breaking change which adds functionality)
- [ x] Code style update (formatting, local variables)
- [ x] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ x] This change requires a documentation update

## Mention any unusual behaviour of your code (Write NA if not)
Any unusual behaviour of your code

## Checklist:

- [ x] My code follows the guidelines of this project.
- [ x] I have performed a self-review of my own code.
- [ x] I have commented my code, particularly whereever it was hard to understand.
- [ x] My changes generate no new warnings.
- [ x] Any dependent changes have been merged and published in downstream modules.

## Screenshots
Add Screenshots to show your changes 

## Additional Info (optional)
Any additional information you want to give

### CODE REVIEW

**Review by abhishek2x — CHANGES_REQUESTED** [review]
Looks fine but there an issue. You have to create the same function `facebookSignIn` two times in different files. Good practice will be if you create all authentication function in a single file and pass them through props.

**Comment by Ankita297** [comment]
okay Sir i will do it .

**Comment by Ankita297** [comment]
@abhishek2x  Sir is it okay now ?

**Review by abhishek2x — APPROVED** [review]
LGTM

**Review by avinashkranjan — APPROVED** [review]
LGTM..💯

**Pull request merged**
