### PR TITLE
added popup message, will time out after 5 secs!

### PR DESCRIPTION
**Pull request by akshay1027**
## Related Issue 

Added popup message that will come when a user enters the website or home page and the message will vanish after 5 secs! 
It's fully responsive and made it following the existing UI colours

Closes: #157 

Example how to mark a checkbox:-
- [x] My code follows the code style of this project.
-->
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, local variables)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## Mention any unusual behaviour of your code (Write NA if not)
Any unusual behaviour of your code
NA

## Checklist:

- [ ] My code follows the guidelines of this project.
- [ ] I have performed a self-review of my own code.
- [ ] I have commented my code, particularly whereever it was hard to understand.
- [ ] My changes generate no new warnings.
- [ ] Any dependent changes have been merged and published in downstream modules.

## Screenshots
This message will Timeout after 5 secs!

### CODE REVIEW

**Comment by akshay1027** [comment]
Please check it out and let me know if you need any changes in this @avinashkranjan! Thank you!

**Comment by avinashkranjan** [comment]
@akshay1027 Kindly Resolve the Conflicts Rest LGTM...

**Review by Utkarsh1999 — CHANGES_REQUESTED** [review]
@akshay1027 , resolve conflicts

**Comment by akshay1027** [comment]
I have made the changes @Utkarsh1999 @avinashkranjan

**Review by Utkarsh1999 — APPROVED** [review]
Looks good to me.

**Review by avinashkranjan — APPROVED** [review]

**Pull request merged**
