### PR TITLE
auto merge the PR from dependabot

### PR DESCRIPTION
**Pull request by Ankita297**
## Related Issue 
auto merge the PR from dependabot

Closes: #168 

### Describe the changes you've made

github action to Automerge the PRs from dependabot bot 

## Type of change

What sort of change have you made:

- [x ] Bug fix (non-breaking change which fixes an issue)
- [ x] New feature (non-breaking change which adds functionality)
- [x ] Code style update (formatting, local variables)
- [x ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x ] This change requires a documentation update

## Mention any unusual behaviour of your code (Write NA if not)
Any unusual behaviour of your code

## Checklist:

- [ x] My code follows the guidelines of this project.
- [x ] I have performed a self-review of my own code.
- [x ] I have commented my code, particularly whereever it was hard to understand.
- [x ] My changes generate no new warnings.
- [x ] Any dependent changes have been merged and published in downstream modules.

## Screenshots
done by Ankita297 · Pull Request #5 · Ankita297_Story - Google Chrome 17-04-2021 20_05_45

## Additional Info (optional)
Any additional information you want to give

### CODE REVIEW

**Comment by Ankita297** [comment]
@avinashkranjan Please review my PR .

**Comment by Ankita297** [comment]
As all the PR made from dependabot will have dependencies label with them

**Comment by Ankita297** [comment]
As all the PR made from dependabot will have dependencies label with them

**Review by Utkarsh1999 — APPROVED** [review]

**Comment by Utkarsh1999** [comment]
@avinashkranjan , you can merge this one if it is required.

**Review by avinashkranjan — APPROVED** [review]

**Pull request merged**
